// The two symbols that opt an executable into the Agility SDK: the D3D12 runtime
// looks for them in the executable's own export table, and when both are there
// it loads D3D12Core.dll from the named subdirectory instead of the copy Windows
// ships. They are only found in the executable — which is why this file is its
// own OBJECT library, linked by each executable through hikari_deploy_d3d12(),
// rather than a source of the RHI.
//
// `unsigned int` and `const char*` are the runtime's UINT and LPCSTR, spelled
// without windows.h so that this translation unit depends on nothing.

extern "C"
{
    /**
     * The Agility SDK release's minor version, generated by CMake from the port —
     * 619 for 1.619.5. The runtime refuses a D3D12Core.dll that disagrees, and the
     * backend checks what the loaded copy exports rather than trusting this.
     */
    __declspec(dllexport) extern const unsigned int D3D12SDKVersion = HIKARI_D3D12_SDK_VERSION;

    /**
     * Relative to the executable. A malformed path fails the first D3D12 call with
     * D3D12_ERROR_INVALID_REDIST rather than falling back to the in-box runtime.
     */
    __declspec(dllexport) extern const char* D3D12SDKPath = ".\\D3D12\\";
}
